### ISSUE TITLE
problem with TLS

### ISSUE THREAD

**Issue by rspadim** [pear/Net_SMTP#14]
hi guys i couldn't send email with gmail, i changed the net/socket php file to avoid tls, but the problem is reported here:
http://osticket.com/forum/discussion/3422/failed-to-configure-email-smtp-settings
im using php 5.6, maybe we should change something at socket creation or use a parameter to change socket options

check this comment:

----
I was getting this error, but even disabling STARTTLS (as several of the above comments suggest) didn't help, as it then reported an authentication error. I found the proper fix for at least my situation.

If you're using PHP 5.6, there are changes to SSL:
http://php.net/manual/en/migration56.openssl.php

Mainly, there is extra verification done on the connection. This verification wasn't done on 5.5 so these issues were ignored. But in my situation, the server was sending the SMTP EHLO command with "localhost" and apparently that causes PHP's new verification to fail.

The solution is to patch osTicket's mail class at /include/pear/Net/SMTP.php - change this line:

$this->_socket_options =$socket_options;

to

$this->_socket_options = array('ssl' => array('verify_peer_name' => false));

This turns the verification off. For my setup, the mail server is on the same local network as the osTicket server, so I'm not overly concerned about the security.

The other solution is to downgrade to PHP 5.5 which doesn't have this extra verification.

It'd be nice if osTicket somehow offered a setting for this so patching the code isn't necessary every time.

**Comment by alecpl** [comment]
Net_SMTP constructor has already the $socket_options argument which allows you to set SSL context options.

**Comment by jparise** [comment]
@alecpl is correct.  That is the correct way to pass options to the underlying socket layer.

I'm not familiar with [osTicket](http://osticket.com/), but it sounds like this is something they could make configuration on their end.

**Comment by rspadim** [comment]
ok, should we include this at documentation/wiki? that's a common problem from what i see at google searchs and 'nobody' explain it "easily"

**Comment by jparise** [comment]
@rspadim: I added a note about this to the documentation in 68420118ac8f9dfe5c4b8cac1bdb955efcd4be21.

**Comment by rspadim** [comment]
nice :)
