### ISSUE TITLE
Tag with semantic versioning

### ISSUE THREAD

**Issue by dol** [pear/Net_SMTP#19]
The current tag schema is not a [Semantic Versioning](http://semver.org/) compatible tag. This would be very helpful to use it together with composer and tag support => https://getcomposer.org/doc/02-libraries.md#tags

**Comment by jparise** [comment]
I went back through the history and added semver-compliant tags. Most of them were imported from the original CVS history and predated semantic versioning.

**Comment by dol** [comment]
Much appreciated. Thx

**Comment by dol** [comment]
Now I can get rid of '@dev-master' and can use the version numbers via https://packagist.org/packages/pear/net_smtp
