### ISSUE TITLE
Undefined variable: last

### ISSUE THREAD

**Issue by timecon-gmbh** [pear/Net_SMTP#23]
I get the following error after upgrading to version 1.7.0:
`PHP Notice: Undefined variable: last in /usr/share/php/Net/SMTP.php on line 1087`
It seems to me that the two lines
`$last = $line;`
and
`$last = $chunk;`
in the function Net_SMTP::data() got lost somehow during the update from version 1.6.3 to 1.7.0.

**Comment by jparise** [comment]
Oh, how embarrassing! Thanks for reporting this. I'll publish a fixed 1.7.1 release shortly.
