### ISSUE TITLE
TLS v1.2 connection problem

### ISSUE THREAD

**Issue by jsmad** [pear/Net_SMTP#25]
Hello,

I'm trying to find out why roundcube won't connect to an SMTP server that uses TLS v1.2 as the only available protocol.

I traced the problem down to TLS v1.2 because when the server enables TLS v1.0, then roundcube is able to connect without problems.

What is also interesting, is that roundcube connects fine to the IMAP server with TLS v1.2, only the SMTP protocol seems to have this problem. Apparently this is because it uses a different library for IMAP.

Upon further investigation, I found that roundcube uses Net_SMTP, which in turn uses PHP contexts. Since I'm using CentOS 7 with PHP 5.4.16 and openssl 1.0.1e, everything supports TLS v1.2 without a problem.

In opening this issue, in hope that you will have more information about TLS v1.2 with Net_SMTP.

Thank you.

**Comment by jparise** [comment]
Sorry, I'm afraid I don't have any more information on this issue. Hopefully someone else can shed more light on the problem.
