### ISSUE TITLE
Bug in SMTP.php, fix included

### ISSUE THREAD

**Issue by scottbentley** [pear/Net_SMTP#27]
There is a bug in Net/SMTP.php.  

1 - Line 1001 of "public function data" you are setting $size to the length of the $headers, if provided separately from the $data.  

2 - Line 1010 if $data is a string, you add strlen($data) to the size. $size now equals strlen($headers)+strlen($data).

3 - Line 1033 if the $headers exist you add them to the quotedata

4 - Line 1066 - Line 1095 you loop over $data, breaking it into chunks, but because the headers were sent separately and output separately on line 1033, but you forgot to remove their length from $size, this loop will attempt to read chars from $data at non-existing indexes.

QUICK FIX: Insert after line 1033
`$size = strlen($data);`

**Comment by jparise** [comment]
Thanks! I think 6a949ef should fix this by removing the header length from `$size` before the remaining data is sent.
