### ISSUE TITLE
STARTTLS issues with certain mail servers

### ISSUE THREAD

**Issue by jaemmer** [pear/Net_SMTP#30]
in NET/SMTP.php

this if statement would always error with STARTTLS failed for many email servers.

```
        if (PEAR::isError($result = $this->socket->enableCrypto(true, $crypto_method))) {
            return $result;
        } elseif ($result !== true) {
            return PEAR::raiseError('STARTTLS failed');
        }
```

I noticed email servers like office365 and yahoo behaved differently than secureserver.net for example

I commented out the raiseError and it worked in all my situations.

**Comment by dimarick** [comment]
Possible your issue related to this line of code:

https://github.com/pear/Net_SMTP/blob/master/Net/SMTP.php#L585

Condition is inversed.

**Comment by jparise** [comment]
@dimarick, what part of this line looks incorrect to you?

https://github.com/pear/Net_SMTP/blob/75e85a480b93a8959f3cb856a38fd693e04b216c/Net/SMTP.php#L585

That looks correct to me. It's check that we aren't already communicating over an SSL connection, per this comment:

```php
        /* We can only attempt a TLS connection if one has been requested,
         * we're running PHP 5.1.0 or later, have access to the OpenSSL
         * extension, are connected to an SMTP server which supports the
         * STARTTLS extension, and aren't already connected over a secure
         * (SSL) socket connection. */
```

**Comment by dimarick** [comment]
@jparise,  strncasecmp($this->host, 'ssl://', 6) will return 0 when host starts with ssl://

See http://php.net/manual/en/function.strncasecmp.php

**Comment by jparise** [comment]
Yes, and this code is checking that it _doesn't_ start with `ssl://` because we don't want to initiate `STARTTLS` over a connection that is already running on a secure (SSL) socket.

**Comment by jparise** [comment]
There hasn't been any activity on this issue in over a year so I'm going to close it. Please reopen it if there's new or additional information.
