### ISSUE TITLE
Support XOAUTH2

### ISSUE THREAD

**Issue by deflomu** [pear/Net_SMTP#31]
Google [encourages](https://developers.google.com/gmail/oauth_overview) the use of the login mechanism XOAUTH2 [1]. It would be great if Net_SMTP had support for this.

Some informations about the protocol and SMTP can be found here: https://developers.google.com/gmail/xoauth2_protocol#smtp_protocol_exchange

**Comment by jparise** [comment]
I'm open to reviewing a patch that adds XOAUTH2 support.

**Comment by thomascube** [comment]
> I'm open to reviewing a patch that adds XOAUTH2 support.

@jparise Please review pull request #55

**Comment by jtuta** [comment]
@jparise I have tested PR #55 on postfix smtp server implementig XOAUTH2 authentication and it worked as expected
