### ISSUE TITLE
Server response for get queued as

### ISSUE THREAD

**Issue by TuxBoy** [pear/Net_SMTP#41]
Hello,

I would like to know if we can configure the response of the server to recover the value of queued as who is get $this->_smpt->getResponse(), because on my server I get this string: "Message queued as .." while in the file smtp.php the chain of Expected character is: "Ok: queued as", I submitted a Pull requests in pear/Mail project to the case where.

Thank you.

**Comment by jparise** [comment]
I'm afraid I'm not sure I understand what you're asking with regard to this project (Net_SMTP). Are you proposing a change or reporting a problem?

**Comment by TuxBoy** [comment]
I'm reporting a problem, It's possible to configure this response on our server "Ok: queued as" ?

**Comment by jparise** [comment]
I think that depends on your specific server software, but I'm not sure. [RFC 2821](https://tools.ietf.org/html/rfc2821) doesn't specify the format of this string, and the Net_SMTP package doesn't do anything with the response string internally. It's just passed back to the caller.

I think you're correct to file this issue for the PEAR Mail package instead.

**Comment by TuxBoy** [comment]
Thank you for your answers.
