### ISSUE TITLE
Request to update license to BSD-2-clause

### ISSUE THREAD

**Issue by roelvanmeer** [pear/Net_SMTP#43]
Currently Net_SMTP is licensed under the PHP 3.01 license. This makes it hard to use this in software that is packaged for Debian, since the Debian standpoint [1] is that this is not a valid license for anything other than PHP itself.

Would you consider updating the license to the BSD-2-clause license?

 [1] https://ftp-master.debian.org/php-license.html

**Comment by chuck** [comment]
I'm alright with this change. -Chuck Hagenbuch

**Comment by jparise** [comment]
It's alright with me, too.

**Comment by ashnazg** [comment]
@chuck @jparise, you guys want me to roll a release for this?

**Comment by chuck** [comment]
Ok by me. :) thanks!


-chuck

**Comment by jparise** [comment]
I'm unclear as to whether we've achieved the legal threshold for re-licensing. Don't _all_ contributors need to grant their consent?

That being said, I have no objection, and this might be a good point for someone other than me to take over maintainer-ship of this package. I haven't used PHP or this package in practice for well over ten years. 😉

**Comment by roelvanmeer** [comment]
I've email Jon, Chuck and Damian about this, since they are mentioned as authors in the file. I had hoped that permission from you three would be enough for re-licensing. That means we only need a response from Damian.

I am not a lawyer though, so I could be wrong. :)

**Comment by demonio669** [comment]
Hi! I also agree with license change

**Comment by ashnazg** [comment]
Others I see with commits specifically on the code file `Net/Smtp.php` are @alecpl , @eehakkin , @dsoares , and @CloCkWeRX .  Everyone, please reply with your opinion on this license change request with respect to your previous contributions to this code package.

**Comment by alecpl** [comment]
I agree.

**Comment by eehakkin** [comment]
Fine by me.

**Comment by dsoares** [comment]
OK.

**Comment by ashnazg** [comment]
Ok @CloCkWeRX , just waiting for you :)

**Comment by ashnazg** [comment]
Looking more closely, @CloCkWeRX reverted his specific commits, so I think we have all the OKs we need.

**Comment by CloCkWeRX** [comment]
Assume I'm a blanket yes to all license changes for all PEAR code
