### ISSUE TITLE
Pointer of resource $data is not rewinded after using fstat (SMTP.php line 1034-1075)

### ISSUE THREAD

**Issue by Juweii** [pear/Net_SMTP#6]
Hello Net_SMTP developer!

Please find the following bugfix for a problem, where the email message is empty using resource mail body (used by horde webmailer):

```
--- SMTP.orig.php       2013-08-26 21:14:43.602400474 +0200
+++ SMTP.php    2013-08-26 21:14:55.801607272 +0200
@@ -1036,6 +1036,7 @@
                 return PEAR::raiseError('Failed to get file size');
             }
             $size += $stat['size'];
+            rewind($data);
         } else {
             $size += strlen($data);
         }
```

Reason: the pointer is not getting resetted after using fstat($data).
Without rewind($data) theres no data on line 1075 to read...

I am not sure if this is caused by a change in PHP (5.3.17).

Best regards,
Juergen

Edit: not sure on how to post code to that issue tracker... Hopefully the bugfix is clear, otherwise please tell me how to post code like [code] ... [/code]

Edit2: Thank you jparise ;)

**Comment by alecpl** [comment]
This is not required, the code works perfectly with Roundcube without the rewind().

**Comment by jparise** [comment]
Thanks, @alecpl.  I'll close this issue based on your experience but we can reopen it if more information comes to light.
