### ISSUE TITLE
A broken symlink in the package makes it impossible to deploy it as part of a CI/CD pipeline

### ISSUE THREAD

**Issue by asiby** [pear/Net_SMTP#62]
**Problem**

The `/docs` directory is not part of the installed files after running `composer`. Than makes the `/README.rst` link invalid.

**Consequence**

During a deployment, we you have chosen run composer in the pipeline. During that process, when the broken symlink is encountered by the `aws cli` (for example), we get `No such file or directory`.

**Mitigation / Workaround**

Delete `/README.rst` right after running `composer install`

**Proposed solution**
- Do no include any symlink in a library, a repo, etc.
- In this case, replace `README.rst` with it's content from the `/docs` directory.

**Comment by jparise** [comment]
Sorry about that! Fixed in [version 1.9.2](https://github.com/pear/Net_SMTP/releases/tag/1.9.2).

**Comment by asiby** [comment]
Thanks
