### ISSUE TITLE
background process and problems with persistent connection

### ISSUE THREAD

**Issue by rspadim** [pear/Net_SMTP#9]
hi guys, i'm with some problems, runnning a background process forever (execute at server startup and continue live forever) with persistent connection, sometimes it don't work and no exception is displayed, i'm running debug parameter set to true, i will try to develop a test case, but i don't know what could i do to solve this problem

thanks guys

**Comment by jparise** [comment]
Related: pear/Net_Socket#4

**Comment by jparise** [comment]
There hasn't been any activity on this issue in over a year so I'm going to close it. Please reopen it if there's new or additional information.
